version: '3.8'
services:
  db:
    container_name: "postgresql"
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: pirate
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
